'''
the below lines were generated by the vscode copilot plugin.

This module defines the data loading logic for the GitHub MDS Tracker pipeline. It includes two resources:
1. `fetch_repo_stats`: Fetches repository statistics for a predefined list of repositories and categorizes them based on their type (Orchestration, Transformation, Storage).
2. `fetch_repo_events`: Fetches recent events for the same set of repositories, categorizes them, and appends the data to the existing dataset.
'''

import dlt
from dlt.sources.helpers import requests

REPOS_TO_TRACK = {
    "Orchestration": ["kestra-io/kestra", "dagster-io/dagster", "apache/airflow"],
    "Transformation": ["dbt-labs/dbt-core", "sqlmesh/sqlmesh"],
    "Storage": ["duckdb/duckdb", "apache/iceberg"]
}

@dlt.resource(name="repo_stats", write_disposition="replace")
def fetch_repo_stats():
    for category, repos in REPOS_TO_TRACK.items():
        for repo_path in repos:
            url = f"https://api.github.com/repos/{repo_path}"
            response = requests.get(url)
            response.raise_for_status()            
            data = response.json()
            data['mds_category'] = category
            yield data

@dlt.resource(name="repo_events", write_disposition="append")
def fetch_repo_events():
    for category, repos in REPOS_TO_TRACK.items():
        for repo_path in repos:
            url = f"https://api.github.com/repos/{repo_path}/events?per_page=100"
            response = requests.get(url)
            response.raise_for_status()
            events = response.json()
            for event in events:
                event['mds_category'] = category
                event['repo_name'] = repo_path
                yield event

if __name__ == "__main__":
    pipeline = dlt.pipeline(
        pipeline_name="github_mds_tracker",
        destination="minio", 
        dataset_name="bronze_github"
    )

    load_info = pipeline.run([fetch_repo_stats, fetch_repo_events])
    print(load_info)